<a href="https://colab.research.google.com/github/aansheeagrwal/Deep-Learning/blob/main/tensor_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90],dtype=tf.float16)
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float16)


In [5]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [6]:
tensor_string = tf.constant(["hello world","hi "])
print(tensor_string)

tf.Tensor([b'hello world' b'hi '], shape=(2,), dtype=string)


In [7]:
import numpy as np

In [8]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [9]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [10]:
# cnostruct an identity matrix, or a branch of matrices
tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)>

In [11]:
tf.eye(2)
[[1., 0.],
 [0., 1.]]


batch_identity = tf.eye(2, batch_shape=[3])
print(batch_identity)
tf.eye(2, num_columns=3)
[[1., 0., 0.],
 [0., 1., 0.]]


tf.Tensor(
[[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]], shape=(3, 2, 2), dtype=float32)


[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]

In [12]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(3*eye_tensor)

tf.Tensor(
[[[3. 0. 0.]
  [0. 3. 0.]
  [0. 0. 3.]]

 [[3. 0. 0.]
  [0. 3. 0.]
  [0. 0. 3.]]], shape=(2, 3, 3), dtype=float32)


In [13]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90],dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(casted_tensor_one_d)
print(tensor_one_d)

tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)
tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [14]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [15]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

])
print(tensor_three_d)


tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [16]:
print(tensor_three_d.shape)

(4, 2, 3)


In [17]:
print(tensor_zero_d.shape)

()


In [18]:
print(tensor_one_d.shape)

(5,)


In [19]:
print(tensor_two_d.shape)

(4, 3)


In [20]:
print(tensor_three_d.ndim)

3


In [21]:
fill_tensor = tf.fill(
    [1,3,4], 5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [22]:
ones_tensor = tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [23]:
ones_tensor = tf.ones(
    [5,3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [24]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [25]:
print(tensor_three_d.shape)

(4, 2, 3)


In [26]:
# shape of tensor 't' is [2,2,3]
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.rank(t) # 3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [27]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [28]:
random_tensor = tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 0.7431281   0.53983694]
 [-1.6046882   0.7653028 ]
 [ 0.98504907 -0.22409596]], shape=(3, 2), dtype=float32)


In [29]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([0.89297986 0.69739676 0.06223106 0.18105352 0.09580696], shape=(5,), dtype=float32)


In [33]:
import tensorflow as tf

tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6]
], dtype=tf.float32)  # Now it's a 3x3 matrix

tensor_two_d_inv = tf.linalg.inv(tensor_two_d)
print("Original Matrix:\n", tensor_two_d.numpy())
print("Inverse Matrix:\n", tensor_two_d_inv.numpy())


Original Matrix:
 [[ 1.  2.  0.]
 [ 3.  5. -1.]
 [ 1.  5.  6.]]
Inverse Matrix:
 [[-11.666667     4.           0.6666667 ]
 [  6.3333335   -2.          -0.33333334]
 [ -3.3333335    1.           0.33333334]]


In [34]:
tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 1.4305115e-06,  1.0000000e+00, -8.9406967e-08],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]], dtype=float32)>

In [35]:
s,u,v = tf.linalg.svd(tensor_two_d)
print(s)
print(u)
print(v)

tf.Tensor([8.8224125  4.915307   0.06918038], shape=(3,), dtype=float32)
tf.Tensor(
[[-0.2156587  -0.23862338 -0.9468634 ]
 [-0.49710995 -0.8077882   0.31679654]
 [-0.84046024  0.539015    0.0555844 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.2887473  -0.4319106   0.8544462 ]
 [-0.80694115 -0.37049824 -0.45997542]
 [-0.515239    0.8223043   0.24154605]], shape=(3, 3), dtype=float32)


In [37]:
import numpy as np

A = np.array([[2, 6, 5, 2],
              [2, -2, 2, 3],
              [1, 5, 4, 0]])

print("Einsum A =: \n")
print(np.einsum('ij -> i', A))  # Correct function name: einsum
print("------------------------------")


Einsum A =: 

[15  5 10]
------------------------------


In [39]:
import tensorflow as tf

batch_size = 2
s_q = 4
s_k = 5
model_size = 8

Q = tf.random.uniform((batch_size, s_q, model_size))
K = tf.random.uniform((batch_size, s_k, model_size))

print("Q shape:", Q.shape)
print("K shape:", K.shape)


Q shape: (2, 4, 8)
K shape: (2, 5, 8)


In [40]:
x = tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded = tf.expand_dims(x, axis = 0)
print(x_expanded)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [41]:
x_squeezed = tf.squeeze(x_expanded, axis = 0)
for i in range(2):
  x_squeezed = tf.squeeze(x_expanded, axis = 0)
print(x_squeezed)

tf.Tensor([[[2 3 4 5]]], shape=(1, 1, 4), dtype=int32)
